[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "volviz"
version = "0.1.0"
authors = [
  { name="Robert J. Paneque-Yunta", email="rpaneque@ucm.es" },
]
description = "Interactive 3D volume slicer for Jupyter Notebooks"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "numpy",
    "matplotlib",
    "ipywidgets",
    "ipympl"
]

[project.urls]
"Homepage" = "https://github.com/RJPaneque/volviz"